### ISSUE TITLE
[Bug ?] CSS Layout / Task Rendering Not OK When adding Subtasks

### ISSUE THREAD

**Issue by mehdiyahyaoui** [kanboard/kanboard#3158]
First of all - again - Kanboard is a Great tool keep up with the good work

### Actual behaviour

When adding a subtask to an existing task the Task Pannel is not rendered
I got only Text and there is no CSS styling

![image](https://cloud.githubusercontent.com/assets/23338414/24397556/7cb42a5a-139e-11e7-9032-e2b8c7868581.png)

Actual Task in dashboard 

![image](https://cloud.githubusercontent.com/assets/23338414/24397768/261ecbfe-139f-11e7-96e9-0c05397af4cd.png)

![image](https://cloud.githubusercontent.com/assets/23338414/24398317/f3796eb4-13a0-11e7-835a-4d723b18f498.png)

### Expected behaviour

Task pane showing correctly 

### Steps to reproduce

1. Log in to the application
2. Create a Project
3. Create a Task
4. Create a subtask within this Task
5. Click on the Task to show the Task Pan

### Configuration

- [ ] Application version: 1.0.41
- [ ] PHP version: 7.1.1
- [ ] PHP SAPI: cgi-fcgi
- [ ] OS version: Windows NT 6.1
- [ ] Database driver: mysql
- [ ] Database version: 10.1.20-MariaDB
- [ ] Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Comment by mehdiyahyaoui** [comment]
Hello 
Can someone share about the issue

Is it a bug or is ther something wrong with the app enivrement 

Data base
PHP
File integrity

the issues is resolved when a perform a downgrade to 1.0.40

**Comment by fguillot** [comment]
Are your sure that everything is installed correctly? do you have errors in your logs?

**Comment by mehdiyahyaoui** [comment]
My log file keep repoting this issues with the 2 version of kanboard 1.0.40 and 1.0.41


![image](https://cloud.githubusercontent.com/assets/23338414/24591410/7776e45c-17f8-11e7-9fe6-678597c568c9.png)

**Comment by crabnky** [comment]
Have the same and it was caused by Time Tracking Editor. All is OK when I delete this plugin.
https://github.com/stinnux/kanboard-timetrackingeditor

**Comment by mehdiyahyaoui** [comment]
> 
Have the same and it was caused by Time Tracking Editor. All is OK when I delete this plugin.
https://github.com/stinnux/kanboard-timetrackingeditor
> 
It worked thnks a lot @crabnky you made my day !

**Comment by alefaucheur** [comment]
Hello and doesn't work with Kanboard 1.0.44 either
 #14
