### ISSUE TITLE
1.2.20 Sub-Task SQL ERROR

### ISSUE THREAD

**Issue by feurer98** [kanboard/kanboard#4905]
### Checklist

- [x] I verified that Kanboard is correctly installed (to the best of my knowledge)
- [x] I checked that the problem does not come from a plugin
- [x] I checked that the problem is not already reported

### Actual behaviour

The task contains three sub-tasks (33% each) of the main task.
When marking the task as completed, this value should now be displayed. However, I get an SQL ERROR that the table main.task_has_subtasks does not exist. 

### Expected behaviour

I get an SQL ERROR that the table main.task_has_subtasks does not exist. 

### Steps to reproduce

Create a new task and create a subtask.
Close it once and close the subtask in the main task.

### Screenshots

![image](https://user-images.githubusercontent.com/45851500/141316573-f36bd1c2-4d94-4474-bb7e-3d21a538dc31.png)

### Configuration

* Application version: 1.2.20
* PHP version: 7.4.23
* PHP SAPI: fpm-fcgi
* HTTP Client: cURL
* OS version: Linux 3.10.0-962.3.2.lve1.5.61.el7.x86_64
* Database driver: sqlite
* Database version: 3.7.17
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44
