### ISSUE TITLE
Cannot reorder subtasks after changing the status

### ISSUE THREAD

**Issue by Mk-00** [kanboard/kanboard#4925]
### Checklist

- [x] I verified that Kanboard is correctly installed
- [x] I checked that the problem does not come from a plugin
- [x] I checked that the problem is not already reported

### Actual behaviour
- Open a task
- Click a subtask checkbox to change the status to running or completed
- Try to reorder subtasks by dragging -> not possible
- Refresh the page -> dragging works again

### Expected behaviour
- Open a task
- Click a subtask checkbox to change the status to running or completed
- Try to reorder subtasks by dragging -> should be possible

### Steps to reproduce
- Create a task
- Create multiple subtasks
- Open the task and check "Actual behaviour"

### Configuration

Application version: 1.2.20
PHP version: 7.3.29-1~deb10u1
PHP SAPI: apache2handler
HTTP Client: cURL
OS version: Linux 4.19.0-18-amd64
Database driver: sqlite
Database version: 3.27.2
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36

**Comment by RainerBielefeld** [comment]
## My Configuration
* KANBOARD Application version: 1.2.22 on all-inkl.com
* PHP version: 7.4.28
* PHP SAPI: fpm-fcgi
* HTTP Client: cURL
* OS version: Linux 4.15.0-177-generic
* Database driver: mysql
* Database version: 5.7.37-nmm1-log
* [Plugins](https://kanboard.org/plugins.html): [Wiki](https://github.com/funktechno/kanboard-plugin-wiki), [ProjectInvitation](https://github.com/ipunkt/KanboardProjectInvitation), [MarkdownPlus](https://github.com/creecros/MarkdownPlus) ad Task2Pdf
* Browser: **SeaMonkey** (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0)

## STR 
1. After having logged in to my [Test Board](https://tickets.kanban.bielefeldundbuss.de/)  with your User Data you got via[ this Task](https://tickets.kanban.bielefeldundbuss.de/?controller=TaskViewController&action=readonly&task_id=34&token=1fe7f29430a6532601dc9ef6ed0dfc4456c6bdebd5c40568d30aee9489ab) by Email:
2. Try to modiy order of Sub-Tasks of [**_#50_**](https://tickets.kanban.bielefeldundbuss.de/?controller=TaskViewController&action=show&task_id=50) by Drag and Drop: Works fine!
3. Add "completed" Checkmark to subtask "3. ..."
4. Try to modify order of Sub-Tasks (interchange (1.) and (2.) by Drag and Drop: 
   No longer works  :disappointed_relieved:
   
## Additional info
a) Same with FF 103.0a1 (2022-06-04) (64-Bit) and Chromium Version 97.0.4692.71 (Offizieller Build) (64-Bit)
b) Same with Chromium  97.0.4692.71 (Offizieller Build) (64-Bit)  
c) There is a simple **Workaround**: Simply "Reload Page" in your Browser! Afterwards reorder will work again.

**Comment by rolandu** [comment]
In the past I experienced the same issue and the workaround by @RainerBielefeld (i.e. reloading the page) did work for me. Since a recent upgrade (I cannot say which version exactly) I am not able to reorder at all, i.e. I can reorder items, however the change is forgotten after reloading the page. I am also on  v1.2.22.

Unfortunately, I am not too familiar with the inner workings of the software. 

A look at the inspector reveals that every reordering is a call like `/?controller=SubtaskController&action=movePosition&task_id=16`, however this results in an error 403 response. I have located the code, however I don't see what is wrong with it: [SubtaskController->movePosition](https://github.com/kanboard/kanboard/blob/b433519686dea7a265ef4fc112cad81e31de9026/app/Controller/SubtaskController.php#L210)...

**Comment by einhirn** [comment]
This seems to be fixed in https://github.com/kanboard/kanboard/commit/c4f9c34f75bfcea445fdb41288cfe063c05438bb which hopefully will be part of 1.2.23 or so - but until then you can just download the [patch](https://github.com/kanboard/kanboard/commit/c4f9c34f75bfcea445fdb41288cfe063c05438bb.patch) and apply it manually using the `patch` program. Or you can just download the updated [`app/controllers/SubtaskController.php` file](https://raw.githubusercontent.com/kanboard/kanboard/776cbe6830f7e32d39a69af07694aa6666d502ba/app/Controller/SubtaskController.php) containing the patch, I checked that [it didn't change anything else since 1.2.22](https://github.com/kanboard/kanboard/compare/v1.2.22...776cbe6830f7e32d39a69af07694aa6666d502ba#diff-e227ad1de298245ded3efe2d23a500d49e9e44402b378f7e2024c2e0b05bcd55) in the linked revision.

**Comment by Mk-00** [comment]
I just upgraded to 1.2.23 but the issue is still there :(
