### ISSUE TITLE
Reordering of subtask is not saved

### ISSUE THREAD

**Issue by arlt** [kanboard/kanboard#4980]
### Checklist

- [x] I verified that Kanboard is correctly installed
- [x] I verified that the problem does not come from a plugin
- [x] I verified that the problem is not already reported
- [x] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour

Reordering of subtask works but the new position is not saved.
In browser network you can see a 403 during move of the subtask.
After reloading, the subtasks are at the previous position.

This worked well in version 1.2.21.

### Expected behaviour

Moved subtask should remain on the new position.

### Steps to reproduce

Create 2 or more subtasks in a task and move them up/down.

### Screenshots

![grafik](https://user-images.githubusercontent.com/2340176/158785325-7b5253b5-f4c8-43e8-bc22-998d9116b3a2.png)

### Addition information

- `$project_id` is 0 regardless of project
see https://github.com/kanboard/kanboard/blob/master/app/Controller/SubtaskController.php#L212
- `$this->helper->user->hasProjectAccess('SubtaskController', 'movePosition', $project_id` is false
see https://github.com/kanboard/kanboard/blob/master/app/Controller/SubtaskController.php#L216
- 403 is coming from ...
see https://github.com/kanboard/kanboard/blob/master/app/Controller/SubtaskController.php#L220

@Chaosmeister Maybe there is connection to `Remove project_id from task URLs` https://github.com/kanboard/kanboard/commit/61e63ef9e012d494864d4a0f0341a8aa2b49c5d6 ?!

### Configuration

- Kanboard version: 1.2.22
- Database type and version: PostgreSQL 10.20
- PHP version: 7.4.28
- OS: CentOS 7.7
- Browser: Edge, Chrome, Firefox

**Comment by Chaosmeister** [comment]
yeah that's possible

thanks for the report!

**Comment by arlt** [comment]
@Chaosmeister tested here - works - thanks! (when) is a new release planned?

**Comment by Chaosmeister** [comment]
releases are somewhat unsteady, as kanboard is in maintenance mode.

concerning the weight of the issue, I'd say a new version will be released in the near future
