### ISSUE TITLE
Field tasks.time_estimated  will be clear when add a new Time Tracking Event

### ISSUE THREAD

**Issue by badpasta** [kanboard/kanboard#5057]
### Checklist

- [x] I verified that Kanboard is correctly installed
- [x] I verified that the problem does not come from a plugin
- [x] I verified that the problem is not already reported
- [x] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour

Field tasks.time_estimated  will be clean when add a new Time Tracking Event

### Expected behaviour

Field tasks.time_estimated  not change when add a new Time Tracking Event

### Configuration

- Kanboard version: 1.2.22
- Database type and version: postgres 14
- PHP version: php 8.2
- OS: Centos 7
- Browser: Chrome Version 105.0.5195.102 (Official Build) (x86_64)
