### ISSUE TITLE
restriction "Project->Task creation is not permitted" does not prevent converting sub-tasks to tasks

### ISSUE THREAD

**Issue by chronopoulos** [kanboard/kanboard#5069]
### Checklist

- [x] I verified that Kanboard is correctly installed
- [x] I verified that the problem does not come from a plugin
- [x] I verified that the problem is not already reported
- [x] I understand that Kanboard is in maintenance mode. It doesn't mean it's abandoned, but there is no significant feature development

### Actual behaviour

In one of my projects, I have a Custom Role "Engineer" which has the restriction "Project->Task creation is not permitted" enabled. To my surprise, users with this role are indeed able to create new tasks by introducing them as sub-tasks and then selecting "Convert to Task".

Referencing [Issue 3304](https://github.com/kanboard/kanboard/issues/3304) as possibly related. Note that I am running Kanboard version 1.2.20 (that issue claims to be resolved with 1.0.45).

### Expected behaviour

I would expect users whose Custom Role has "Project->Task creation is not permitted", to not be able to create new tasks by any means.

### Steps to reproduce

(as project owner)
1. Create Custom Role "Engineer"
2. Add a Project Restriction for this Custom Role: Task creation is not permitted
3. Add a user TestUser to the project with the role of Engineer
(as TestUser)
4. Open any task currently in the project.
5. Add a sub-task to the task
6. Click on the gear icon, select "Convert to task", click OK to confirm

### Configuration

- Kanboard version: 1.2.20
- Database type and version: sqlite 3.34.1
- PHP version: 7.4.28
- OS: Debian 11, kernel 5.10.0-8-amd64
- Browser: Firefox and Chrome
